### ISSUE TITLE
rdrand doesn't work on windows.

### ISSUE THREAD

**Issue by marshonhuckleberry** [stillson/rdrand#10]
1. installing python 3.8 in windows 10 x64
2. starting cmd and typing "pip install ." in unzipped folder or "pip install rdrand"
3. big failure, errors, etc.
rdrand has a dedicated documentation website also readme information but everything is crap, only useless words, nothing actually usefull to make it work, my intuition says noone will solve this issue

**Comment by stillson** [comment]
Yes, this is known problem. I don't have a windows machine so there is no way I can fix this. If you have access to a compiler, I would be happy to take patches.

**Comment by bashtage** [comment]
There is a version in [randomgen](https://bashtage.github.io/randomgen/bit_generators/rdrand.html) that works with Windows (and has wheels available).  It is for either direct use getting 64-bit values or with a NumPy `Generator` object.

**Comment by stillson** [comment]
Umm, this is still a problem.

**Comment by ZOusama7** [comment]
I finally got it to work with windows, Here are the steps i took: (keep in mind that some steps may be unnecessary )
1) download mingw64 (0x86_64,Posix ).
2) add mingw64 bin directory to The OS' PATH variable.
3) download "rdrand-1.5.0.tar.gz" from pypi.
4) extract it into "C:\rdrand-1.5.0\" to make it easier to work with
5) change the "cpuid" function in rdrand.c as follows: **(only to solve the "invalid instruction suffix for `push'" error)**


```
cpuid(unsigned int op, unsigned int subfunc, unsigned int reg[4])
{

#if USING_GCC && IS64BIT
    __cpuid(reg, op, subfunc);
#else
    asm volatile("pushl %%ebx      \n\t" /* save %ebx */
                 "cpuid            \n\t"
                 "movl %%ebx, %1   \n\t" /* save what cpuid just put in %ebx */
                 "popl %%ebx       \n\t" /* restore the old %ebx */
                 : "=a"(reg[0]), "=r"(reg[1]), "=c"(reg[2]), "=d"(reg[3])
                 : "a"(op), "c"(subfunc)
                 : "cc");
#endif
}
```
To :

```
cpuid(unsigned int op, unsigned int subfunc, unsigned int reg[4])
{

#if USING_GCC && IS64BIT
    __cpuid(reg, op, subfunc);
#elif USING_GCC
	asm volatile("push %%rbx      \n\t" /* save %ebx */
                 "cpuid            \n\t"
                 "movl %%ebx, %1   \n\t" /* save what cpuid just put in %ebx */
                 "pop %%rbx       \n\t" /* restore the old %ebx */
                 : "=a"(reg[0]), "=r"(reg[1]), "=c"(reg[2]), "=d"(reg[3])
                 : "a"(op), "c"(subfunc)
                 : "cc");
#else
    asm volatile("pushl %%ebx      \n\t" /* save %ebx */
                 "cpuid            \n\t"
                 "movl %%ebx, %1   \n\t" /* save what cpuid just put in %ebx */
                 "popl %%ebx       \n\t" /* restore the old %ebx */
                 : "=a"(reg[0]), "=r"(reg[1]), "=c"(reg[2]), "=d"(reg[3])
                 : "a"(op), "c"(subfunc)
                 : "cc");
#endif
}
```
6) change ("C:\Path\to\python_env\Lib\distutils\cygwinccompiler.py") as follows: **(only to solve the error: \path\to\mingw\bin\ld.exe: cannot find -msvcr140)**

        ```
        ## Original :
        # elif int(msc_ver) >= 1900:
            ## VS2015 / MSVC 14.0
            # return ['msvcr140']
        ## End Original.
        
        elif int(msc_ver) >= 1900:
          # Visual Studio 2015 / Visual C++ 14.0
          # "msvcr140.dll no longer exists" http://blogs.msdn.com/b/vcblog/archive/2014/06/03/visual-studio-14-ctp.aspx
          return ['vcruntime140']
          
        ## End Patch.
       ```
7) copy ("C:\Path\to\python_env\vcruntime140.dll") to clipboard  **(only to solve the error: ld.exe: cannot find -lvcruntime140)**
and paste it in C:\Path\to\mingw64\lib\gcc\x86_64-w64-mingw32\8.1.0(or your version).

8) open anaconda prompt and activate your envirement ( or just CMD if you don't use anaconda )  and do this commands:
```
cd c:\rdrand-1.5.0
python setup.py build -c mingw32
python setup.py install
```

( a bit late but maybe ( i didn't try it) you can just recompress the rdrand-1.5.0 dir to rdrand-1.5.0.tar.gz, then follow this ([tutorial](https://www.py4u.net/discuss/12600)) to make pip use mingw32 compiler, then just `pip install c:\rdrand-1.5.0.tar.gz`)

**Comment by ZOusama7** [comment]
for those who just want the wheel this is the wheel for windows x64 python 3.
[rdrand-1.5.0-cp38-cp38-win_amd64.whl.zip](https://github.com/stillson/rdrand/files/7565388/rdrand-1.5.0-cp38-cp38-win_amd64.whl.zip)
8

**Comment by ZOusama7** [comment]
btw @stillson , i'm not sure but i think that the line 448 in rdrand.c which is:
`    fill_buf_using_rdrand(udata, nq);`
should be:
`    fill(udata, nq);`
or else get_bytes will always return rdrand_get_bytes whether it's called from rdrand_get_bytes or rdseed_get_bytes

**Comment by zittox** [comment]
unable to install in win 10 / python 3.10

do i need c++ to install this ?

"""error: Microsoft Visual C++ 14.0 or greater is required.""




Collecting rdrand
  Using cached rdrand-1.5.0.tar.gz (6.2 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: rdrand
  Building wheel for rdrand (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'd:\py\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\zuckforks\\AppData\\Local\\Temp\\pip-install-73knr4q4\\rdrand_f72a1e0e5ead4268a69842ace028799a\\setup.py'"'"'; __file__='"'"'C:\\Users\\zuckforks\\AppData\\Local\\Temp\\pip-install-73knr4q4\\rdrand_f72a1e0e5ead4268a69842ace028799a\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\zuckforks\AppData\Local\Temp\pip-wheel-futcuvrp'
       cwd: C:\Users\zuckforks\AppData\Local\Temp\pip-install-73knr4q4\rdrand_f72a1e0e5ead4268a69842ace028799a\
  Complete output (52 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.10
  copying rdrand.py -> build\lib.win-amd64-3.10
  running build_ext
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\zuckforks\AppData\Local\Temp\pip-install-73knr4q4\rdrand_f72a1e0e5ead4268a69842ace028799a\setup.py", line 3, in <module>
      setup(name='rdrand',
    File "d:\py\lib\site-packages\setuptools\_distutils\core.py", line 148, in setup
      return run_commands(dist)
    File "d:\py\lib\site-packages\setuptools\_distutils\core.py", line 163, in run_commands
      dist.run_commands()
    File "d:\py\lib\site-packages\setuptools\_distutils\dist.py", line 967, in run_commands
      self.run_command(cmd)
    File "d:\py\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
      cmd_obj.run()
    File "d:\py\lib\site-packages\wheel\bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "d:\py\lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "d:\py\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
      cmd_obj.run()
    File "d:\py\lib\site-packages\setuptools\_distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "d:\py\lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "d:\py\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
      cmd_obj.run()
    File "d:\py\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
      _build_ext.run(self)
    File "d:\py\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 339, in run
      self.build_extensions()
    File "d:\py\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 448, in build_extensions
      self._build_extensions_serial()
    File "d:\py\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 473, in _build_extensions_serial
      self.build_extension(ext)
    File "d:\py\lib\site-packages\setuptools\command\build_ext.py", line 202, in build_extension
      _build_ext.build_extension(self, ext)
    File "d:\py\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 528, in build_extension
      objects = self.compiler.compile(sources,
    File "d:\py\lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 327, in compile
      self.initialize()
    File "d:\py\lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 224, in initialize
      vc_env = _get_vc_env(plat_spec)
    File "d:\py\lib\site-packages\setuptools\msvc.py", line 316, in msvc14_get_vc_env
      return _msvc14_get_vc_env(plat_spec)
    File "d:\py\lib\site-packages\setuptools\msvc.py", line 270, in _msvc14_get_vc_env
      raise distutils.errors.DistutilsPlatformError(
  setuptools._distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  ----------------------------------------
  ERROR: Failed building wheel for rdrand
  Running setup.py clean for rdrand
Failed to build rdrand
Installing collected packages: rdrand
    Running setup.py install for rdrand ... error
    ERROR: Command errored out with exit status 1:
     command: 'd:\py\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\zuckforks\\AppData\\Local\\Temp\\pip-install-73knr4q4\\rdrand_f72a1e0e5ead4268a69842ace028799a\\setup.py'"'"'; __file__='"'"'C:\\Users\\zuckforks\\AppData\\Local\\Temp\\pip-install-73knr4q4\\rdrand_f72a1e0e5ead4268a69842ace028799a\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\zuckforks\AppData\Local\Temp\pip-record-0_5he0ym\install-record.txt' --single-version-externally-managed --compile --install-headers 'd:\py\Include\rdrand'
         cwd: C:\Users\zuckforks\AppData\Local\Temp\pip-install-73knr4q4\rdrand_f72a1e0e5ead4268a69842ace028799a\
    Complete output (10 lines):
    running install
    d:\py\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.10
    copying rdrand.py -> build\lib.win-amd64-3.10
    running build_ext
    error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'd:\py\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\zuckforks\\AppData\\Local\\Temp\\pip-install-73knr4q4\\rdrand_f72a1e0e5ead4268a69842ace028799a\\setup.py'"'"'; __file__='"'"'C:\\Users\\zuckforks\\AppData\\Local\\Temp\\pip-install-73knr4q4\\rdrand_f72a1e0e5ead4268a69842ace028799a\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\zuckforks\AppData\Local\Temp\pip-record-0_5he0ym\install-record.txt' --single-version-externally-managed --compile --install-headers 'd:\py\Include\rdrand' Check the logs for full command output.

**Comment by jdb130496** [comment]
I could finally make this work using following steps. I did it through Powershell with Python 3.12 (Windows 11) - Although Msys and Cygwin options will also work equally fine. Just wanted to do it in the latest Python version. Before mentioning steps, quite appreciate of the guidance by ghost above (user account deleted but that unknown user worthy of large credit for this success). I used many of those steps but combined them with other changes. Steps (To be honest I am not a developer or an expert like others here but actually an accountant by profession but with the combination of ghost help and bing AI co-pilot I could compile successfully): 

1. Cloning this repository and navigating to that folder.
2. change rdrand.c - cpuid -  as below (Already guidance in detail as above):

cpuid(unsigned int op, unsigned int subfunc, unsigned int reg[4])
{

#if USING_GCC && IS64BIT
    __cpuid(reg, op, subfunc);
#elif USING_GCC
	asm volatile("push %%rbx      \n\t" /* save %ebx */
                 "cpuid            \n\t"
                 "movl %%ebx, %1   \n\t" /* save what cpuid just put in %ebx */
                 "pop %%rbx       \n\t" /* restore the old %ebx */
                 : "=a"(reg[0]), "=r"(reg[1]), "=c"(reg[2]), "=d"(reg[3])
                 : "a"(op), "c"(subfunc)
                 : "cc");
#else
    asm volatile("pushl %%ebx      \n\t" /* save %ebx */
                 "cpuid            \n\t"
                 "movl %%ebx, %1   \n\t" /* save what cpuid just put in %ebx */
                 "popl %%ebx       \n\t" /* restore the old %ebx */
                 : "=a"(reg[0]), "=r"(reg[1]), "=c"(reg[2]), "=d"(reg[3])
                 : "a"(op), "c"(subfunc)
                 : "cc");
#endif
}

3. Change of Setup.py as under - distutils deprecated so changed as under:

from setuptools import setup, Extension
import os

os.environ["CC"] = "gcc"
os.environ["CXX"] = "g++"

setup(
    name='rdrand',
    version='1.4.9',
    description="Python interface to Intel hardware rng",
    long_description= "".join(open('rdrandom.rst').readlines()),
    author="Chris Stillson",
    author_email="stillson@gmail.com",
    url='https://github.com/stillson/rdrand',
    license="New BSD license",
    ext_modules=[Extension('_rdrand', ['rdrand.c'])],
    py_modules = ['rdrand'],
    keywords = ['rdrand', 'rdseed', "intel","hardware","random","number","generator","rng"],
    data_files=[('share', ['rdrandom.rst'])],
    classifiers = ["Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: BSD License",
        "Programming Language :: Python",
        "Programming Language :: Python :: 2",
        "Programming Language :: Python :: 3",
        "Topic :: Security",
        "Topic :: Security :: Cryptography",],
    extras_require={
        'tests': [],
        'docs': [
            'sphinx >= 1.4',
            'sphinx_rtd_theme']}
)

4. vcruntime file copy:

copy ("C:\Path\to\python_env\vcruntime140.dll") to clipboard (only to solve the error: ld.exe: cannot find -lvcruntime140)
and paste it in C:\Path\to\mingw64\lib\gcc\x86_64-w64-mingw32\8.1.0(or your version). My path was : D:\Programs\mingw64\lib\gcc\x86_64-w64-mingw32\13.2.0

5. From rdrand directory issue command:

py setup.py build -c mingw32

6. finally (in rdrand folder):

pip install .  (avoid using py setup.py install as eggs will be deprecated in future - I saw warning doing this way for another package / library)

**Comment by jdb130496** [comment]
Prerequisites:
mingw64 tool-chain required, which includes - gcc / g++, etc. I used bash in Msys to build this package - did not use Visual Studio.

Steps in brief:

1. Cloning this repository and navigating to that folder.
2. change rdrand.c - cpuid -  as below (Already guidance in detail as above):

cpuid(unsigned int op, unsigned int subfunc, unsigned int reg[4])
{

#if USING_GCC && IS64BIT
    __cpuid(reg, op, subfunc);
#elif USING_GCC
	asm volatile("push %%rbx      \n\t" /* save %ebx */
                 "cpuid            \n\t"
                 "movl %%ebx, %1   \n\t" /* save what cpuid just put in %ebx */
                 "pop %%rbx       \n\t" /* restore the old %ebx */
                 : "=a"(reg[0]), "=r"(reg[1]), "=c"(reg[2]), "=d"(reg[3])
                 : "a"(op), "c"(subfunc)
                 : "cc");
#else
    asm volatile("pushl %%ebx      \n\t" /* save %ebx */
                 "cpuid            \n\t"
                 "movl %%ebx, %1   \n\t" /* save what cpuid just put in %ebx */
                 "popl %%ebx       \n\t" /* restore the old %ebx */
                 : "=a"(reg[0]), "=r"(reg[1]), "=c"(reg[2]), "=d"(reg[3])
                 : "a"(op), "c"(subfunc)
                 : "cc");
#endif
}

3. Change of Setup.py: distutils deprecated so changed as under:

from setuptools import setup, Extension
import os

os.environ["CC"] = "gcc"
os.environ["CXX"] = "g++"

setup(
    name='rdrand',
    version='1.5.0',
    description="Python interface to Intel hardware rng",
    long_description= "".join(open('rdrandom.rst').readlines()),
    author="Chris Stillson",
    author_email="stillson@gmail.com",
    url='https://github.com/stillson/rdrand',
    license="New BSD license",
    ext_modules=[Extension('_rdrand', ['rdrand.c'])],
    py_modules = ['rdrand'],
    keywords = ['rdrand', 'rdseed', "intel","hardware","random","number","generator","rng"],
    data_files=[('share', ['rdrandom.rst'])],
    classifiers = ["Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: BSD License",
        "Programming Language :: Python",
        "Programming Language :: Python :: 2",
        "Programming Language :: Python :: 3",
        "Topic :: Security",
        "Topic :: Security :: Cryptography",],
    extras_require={
        'tests': [],
        'docs': [
            'sphinx >= 1.4',
            'sphinx_rtd_theme']}
)

4. vcruntime file copy:

copy ("C:\Path\to\python_env\vcruntime140.dll") to clipboard (only to solve the error: ld.exe: cannot find -lvcruntime140)
and paste it in C:\Path\to\mingw64\lib\gcc\x86_64-w64-mingw32\8.1.0(or your version). My path was : D:\Programs\mingw64\lib\gcc\x86_64-w64-mingw32\13.2.0

5. From rdrand directory issue command:

py setup.py build -c mingw32

6. finally (in rdrand folder):

pip install .  (avoid using py setup.py install as eggs will be deprecated in future - I saw warning doing this way for another package / library)

..... Update ... 02/25/2025:

As stated above (ghost), I further modified rdrand.c  - reproducing verbatim what he has mentioned - except that it was line 440 in my case instead of line 448.

"btw @stillson , i'm not sure but i think that the line 448 in rdrand.c which is:
    fill_buf_using_rdrand(udata, nq);
should be:
    fill(udata, nq);
or else get_bytes will always return rdrand_get_bytes whether it's called from rdrand_get_bytes or rdseed_get_bytes"

Needed to change this part in rdrand.c as bcopy gave compilation error in msys on mingw gcc compilation:

if(num_chars)
    {
        rando = quad();
        //bcopy((char*)&rando, &data[num_quads * 8], num_chars);
	memcpy(&data[num_quads * 8], (char*)&rando, num_chars);
    }
